let description = document.getElementById("desc");
let bmi = document.getElementById("bmi").innerText;
let num = parseInt(bmi);

// description.innerHTML = "test " + num

if(num < 18.5){
    description.innerHTML = "Although being lean can often be healthy, being underweight can be a concern if it's the result of poor nutrition or if you are pregnant or have other health concerns. So, if you're underweight, see your doctor or dietitian for an evaluation. Together, you can plan how to meet your goal weight. Here are some healthy ways to gain weight when you're underweight; Eat more frequently. When you're underweight, you may feel full faster. Eat five to six smaller meals during the day rather than two or three large meals. Choose nutrient-rich foods. As part of an overall healthy diet, choose whole-grain breads, pastas and cereals; fruits and vegetables; dairy products; lean protein sources; and nuts and seeds. Try smoothies and shakes. Don't fill up on diet soda, coffee and other drinks with few calories and little nutritional value. Instead, drink smoothies or healthy shakes made with milk and fresh or frozen fruit, and sprinkle in some ground flaxseed. In some cases, a liquid meal replacement may be recommended. Watch when you drink. Some people find that drinking fluids before meals blunts their appetite. In that case, it may be better to sip higher calorie beverages along with a meal or snack. For others, drinking 30 minutes after a meal, not with it, may work. Make every bite count. Snack on nuts, peanut butter, cheese, dried fruits and avocados. Have a bedtime snack, such as a peanut butter and jelly sandwich, or a wrap sandwich with avocado, sliced vegetables, and lean meat or cheese. Top it off. Add extras to your dishes for more calories — such as cheese in casseroles and scrambled eggs, and fat-free dried milk in soups and stews. Have an occasional treat. Even when you're underweight, be mindful of excess sugar and fat. An occasional slice of pie with ice cream is OK. But most treats should be healthy and provide nutrients in addition to calories. Bran muffins, yogurt and granola bars are good choices. Exercise. Exercise, especially strength training, can help you gain weight by building up your muscles. Exercise may also stimulate your appetite.";
}
else if(num > 18.5 && bmi < 22.9){
    description.innerHTML = "Many things can affect your weight, including genetics, age, gender, lifestyle, family habits and culture, sleep, and even where you live and work. Some of these factors can make it hard to lose weight or keep weight off. But being active and choosing healthy foods has health benefits for everyone—no matter your age or weight. It’s important to choose nutrient-dense foods and be active at least 150 minutes per week. As a rule of thumb: To keep your weight the same, you need to burn the same number of calories as you eat and drink, To lose weight, burn more calories than you eat and drink, To gain weight, burn fewer calories than you eat and drink.";
}
else if(num > 22.9 && bmi < 29.9){
    description.innerHTML = "Healthful meals and snacks should form the foundation of the human diet. A simple way to create a meal plan is to make sure that each meal consists of 50 percent fruit and vegetables, 25 percent whole grains, and 25 percent protein. Total fiber intake should be 25–30 gramsTrusted Source (g) daily. Eliminate trans fats from the diet, and minimize the intake of saturated fats, which has a strong link with the incidence of coronary heart disease. Instead, people can consume monounsaturated fatty acids (MUFA) or polyunsaturated fatty acids (PUFA), which are types of unsaturated fat.  The following foods are healthful and often rich in nutrients;fresh fruits and vegetables, fish, legumes, nuts, seeds, whole grains, such as brown rice and oatmeal. Foods to avoid eating include; ,foods with added oils, butter, and sugar, fatty red or processed meats, baked goods, bagels, white bread, processed foods. In some cases, removing certain foods from the diet might cause a person to become deficient in some necessary vitamins and minerals. A nutritionist, dietitian, or another healthcare professional can advise a person how to get enough nutrients while they are following a weight loss program.";
}
else{
    description.innerHTML = "Consume less bad fat and more good fat Contrary to the belief behind the low-fat diet craze of the ’90s, not all fat is bad. ATrusted Source 2017 studyTrusted Source published in the Nutrition Journal showed that intake of healthy dietary fats, such as polyunsaturated fats, can improve cholesterol levels and reduce obesity risk. Consume less processed and sugary foods According to a 2016 studyTrusted Source published in The American Journal of Clinical Nutrition,consumption of processed and ultra-processed foods is linked to a higher risk of obesity. Many processed foods are high in fat, salt, and sugar, which can encourage overeating. Eat more servings of vegetables and fruits. The daily recommendation for fruit and vegetable intake is five to nine servings per day for adults. Filling your plate with veggies and fruit can help keep calories reasonable and reduce the risk of overeating. Eat plenty of dietary fiber. Studies continue to show that dietary fiber plays a role in weight maintenance. One 2012 trialTrusted Source found that people who took a fiber complex supplement three times daily for 12 weeks lost up to 5 percent of their body weight. Focus on eating low–glycemic index foods. The glycemic index (GI) is a scale used to measure how quickly a food item will raise your blood sugar. Focusing on low-GI foods can help keep blood sugar levels steadier. Keeping your blood glucose levels steady can help with weight management. Get the family involved in your journey. Social support isn’t just for children and teens — it’s important for adults to feel supported too. Whether cooking with family or going on walks with friends, getting people involved can help to encourage a healthy lifestyle. Engage in regular aerobic activity. Incorporating regular physical activity into your schedule is important for maintaining or losing weight, among other benefits. The CDCTrusted Source recommends 150 minutes of moderate aerobic activity or 75 minutes of vigorous aerobic activity per week. Incorporate a weight training regimen. Weight training is just as important to weight maintenance as aerobic activity. In addition to weekly aerobic activity, the WHO recommends weight training that involves all your major muscles at least two times per week. Focus on reducing daily stress. Stress can have many effects on the body and mind.";
}